#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$DB_KEYCLOAK_USER" PASSWORD '$DB_KEYCLOAK_PASSWORD';
    CREATE DATABASE "$DB_KEYCLOAK_DATABASE";
    GRANT ALL PRIVILEGES ON DATABASE "$DB_KEYCLOAK_DATABASE" TO "$DB_KEYCLOAK_USER";
EOSQL